trasfondos = {"Acólito": {"Habilidades":["Perspicacia", "Religión"],
                          "Herramientas_a_elegir": 0,
                          "Herramientas":[],
                          "Idiomas_a_elegir": 1,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "un símbolo sagrado (un regalo de cuando entraste en el sacerdocio), un libro de oraciones o rueda de plega-rias, 5 barritas de incienso, vestiduras, un cconjunto de ropa común y una bolsa que contiene 15 po.",
                          "Rasgo": "REFUGIO DE LOS FIELES Como acólito, mereces el respeto de aquellos que comparten tu fe y puedes realizar las ceremonias religiosas de tu deidad. Tus compañeros de aventuras y tú podéis recibir sanación gratuita y atención en un templo, santuario, u otra presencia establecida de tu fe, aunque debes proporcionar los compo-nentes materiales necesarios para los conjuros. Aquellos que comparten tu religión te podrán proporcionar (pero sólo a ti) un estilo de vida modesto. También podrías tener vínculos con un templo específico dedicado a tu deidad o panteón y tener una residencia allí. Podría tratarse del templo que utilizas para realizar los servi-cios, si mantienes una buena relación con la comunidad, o un templo en el que has encontrado un nuevo hogar. Mientras estés cerca de tu templo, puedes llamar a los sacerdotes para que te asistan, siempre y cuando la ayuda que solicitas no ponga en peligro a quien la realiza y permanezcas en buena relación con tu templo."
                          },
              "Artesano Gremial": {"Habilidades":["Perspicacia", "Persuasión"],
                          "Herramientas_a_elegir" : 1,
                          "Herramientas":["Herramientas de albañil", "Herramientas de alfarero", "Herramientas de carpintero", "Herramientas de cartógrafo", "Herramientas de constructor", "Herramientas de herrero","Herramientas de joyero","Herramientas de peletero", "Herramientas de pintor", "Herramientas de soplador de vidrio","Herramientas de tallador de madera","Herramientas de tejedor", "Herramientas de zapatero", "Suministros de alquimista","Suministros de calígrafo","Suministros de cervecero", "Utensilios de cocinero", "Kit de disfraz", "Kit de falsificación","Herramientas de ladrón","Herramientas de navegante"],
                          "Idiomas_a_elegir": 1,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "un set de herramientas de artesano (de tu elección), una carta de introducción de tu gremio, una muda de ropas de viaje, una bolsa que contiene 15 po.",
                          "Rasgo": "MEMBRESÍA DEL GREMIO Como un miembro de un gremio establecido y respetado, tienes ciertos beneficios que te provee tu membresía. Tus compañeros de gremio te proveerán alojamiento y comida si la necesitas y pagarán por tu funeral si es necesario. En algunos pueblos y ciudades, un salón del gremio ofrece un lugar central para encontrarse con otros miembros de tu profesión, que puede ser un buen lugar para conocer potenciales patrones, aliados o empleados. Los gremios a menudo poseen gran peso político. Si eres acusado de un crimen, tu gremio te apoyará si es factible presentar una buena defensa o si tu crimen es justificable. También ganas acceso a poderosas figuras políticas a través del"
                          },
              "Artista": {"Habilidades":["Acrobacias", "Interpretación"],
                          "Herramientas_a_elegir" : 2,
                          "Herramientas":["kit de disfraz", "Caramillo", "Cuerno", "Dulcimer", "Flauta", "Flauta de pan", "Gaita", "Laúd", "Lira", "Tambor", "Viola"],
                          "Idiomas_a_elegir": 0,
                          "Idiomas":[],
                          "Equipo": "un instrumento musical (de tu elección), el favor de un admirador (una carta de amor, un mechón de pelo o una baratija), un disfraz y una bolsa que contiene 15 po.",
                          "Rasgo": "Siempre puedes encontrar un lugar para actuar, por lo general en una posada o taberna, pero posiblemente en un circo, un teatro o incluso en la corte de un noble. En ese lugar, recibirás alojamiento y comida modesta o confortable (dependiendo de la calidad del establecimiento) gratitos, siempre y cuando actúes cada noche. Además, tu actuación te convierte en algo así como una figura local. Cuando unos desconocidos te reconozcan en una ciudad en la que hayas actuado, por lo general mostrarán simpatía hacia tu persona."
                          },
              "Charlatán": {"Habilidades":["Engañar", " Juego de Manos"],
                            "Herramientas_a_elegir": 2,
                            "Herramientas":["kit de disfraz", "kit de falsificación"],
                            "Idiomas_a_elegir": 0,
                            "Idiomas":[],
                            "Equipo": "un conjunto de ropa fina, un kit de disfraz, herramientas de estafa de tu elección (diez botellas con tapón llenas con un líquido de color, unos dados cargados, una baraja de cartas marcadas, o un anillo de sello de un duque imaginario) y una bolsa con 15 po.",
                            "Rasgo": "IDENTIDAD FALSA Te has creado una segunda identidad que incluye documentación, contactos establecidos y disfraces que te permiten asumir ese personaje. Además, puedes falsificar documentos oficiales y cartas personales, siempre y cuando hayas visto un ejemplo de la clase de documento o escritura que estás tratando de copiar."
                          },
              "Criminal": {"Habilidades":["Engañar", "Sigilo"],
                           "Herramientas_a_elegir": 2,
                            "Herramientas":["Juego de cartas", "Juego de dados", "Herramientas de ladrón"],
                           "Idiomas_a_elegir": 0,
                            "Idiomas":[],
                            "Equipo": "una barreta, un conjunto de ropa común oscura, incluyendo una capucha, y una bolsa que contiene 15 po.",
                            "Rasgo": "CONTACTO CRIMINAL Tienes un contacto de confianza que actúa como enlace con una red de delincuentes. Sabes cómo hacerles llegar mensajes y te los envíen mediante ese contacto, incluso a grandes distancias; específicamente, conoces los mensajeros locales, conductores de caravana corruptos y marineros de mala muerte que te pueden entregar mensajes."
                          },
              "Ermitaño": {"Habilidades":["Medicina", "Religión"],
                           "Herramientas_a_elegir": 1,
                          "Herramientas":["Kit de herborista"],
                           "Idiomas_a_elegir": 1,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "un rollo de pergamino lleno de notas de tus estudios o plegarias, una frazada de invierno, una muda de ropa común, un kit de herboristería y una bolsa con 5 po.",
                          "Rasgo": "DESCUBRIMIENTO La reclusión pacífica de tu extendido aislamiento te dio acceso a un único y poderoso descubrimiento. La exacta naturaleza de esta revelación depende de la naturaleza de tu reclusión. Podría ser una gran verdad acerca del cosmos, las deidades, los seres poderosos de otros planos o las fuerzas de la naturaleza. Podría ser un sitio que nadie más vio nunca. Podrías haber descubierto un hecho que fue olvidado hace mucho, o desenterrado alguna reliquia del pasado que podría reescribir la historia. Podría ser información potencialmente dañina para la gente que te consignó al exilio, y he ahí la razón por la cual regresas a la sociedad. Trabaja con tu DM para determinar los detalles de tu descubrimiento y su impacto en la campaña."
                          },
              "Forastero": {"Habilidades":["Atletismo", "Supervivencia"],
                            "Herramientas_a_elegir": 1,
                          "Herramientas":["Caramillo", "Cuerno", "Dulcimer", "Flauta", "Flauta de pan", "Gaita", "Laúd", "Lira", "Tambor", "Viola"],
                            "Idiomas_a_elegir": 1,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "un bastón, una trampa de caza, un trofeo de un animal que mataste, un conjunto de ropa de viajero y una bolsa que contiene 10 po.",
                          "Rasgo": "VIAJERO Tienes una excelente memoria para los mapas y la geografía y siempre puedes recordar la disposición general del terreno, los asentamientos y otras circunstancias de entorno que te rodea. Además, puedes encontrar comida y agua fresca para ti y para otras cinco personas cada día, siempre y cuando la tierra tenga bayas, algo de caza menor, agua y cosas por el estilo."
                          },
              "Héroe del Pueblo": {"Habilidades":["Trato con animales", "Supervivencia"],
                                   "Herramientas_a_elegir": 2,
                          "Herramientas":["Herramientas de albañil", "Herramientas de alfarero", "Herramientas de carpintero",
                      "Herramientas de cartógrafo", "Herramientas de constructor", "Herramientas de herrero","Herramientas de joyero",
                      "Herramientas de peletero", "Herramientas de pintor", "Herramientas de soplador de vidrio",
                      "Herramientas de tallador de madera","Herramientas de tejedor", "Herramientas de zapatero", "Suministros de alquimista",
                      "Suministros de calígrafo","Suministros de cervecero", "Utensilios de cocinero", "Kit de disfraz", "Kit de falsificación",
                      "Herramientas de ladrón","Herramientas de navegante", "Vehículos (terrestres)"],
                                   "Idiomas_a_elegir": 0,
                          "Idiomas":[],
                          "Equipo": " un conjunto de herramientas de artesano (de tu elección), una pala, una olla de hierro, un conjunto de ropa común y una bolsa que contiene 10 po.",
                          "Rasgo": "HOSPITALIDAD RÚSTICA Dado que vienes de las filas de la gente común, encajas entre ellos con facilidad. Puedes encontrar un lugar para esconderte, descansar o recuperarte entre otros plebeyos, a menos que hayas demostrado ser un peligro para ellos. Te protegerán de la ley o de cualquier otra persona que te busque, aunque no arriesgarán sus vidas por ti."
                          },
              "Huérfano": {"Habilidades":["Juego de Manos", "Sigilo"],
                           "Herramientas_a_elegir": 2,
                          "Herramientas":["kit de disfraz", "herramientas de ladrón"],
                           "Idiomas_a_elegir": 0,
                          "Idiomas":[],
                          "Equipo": "un pequeño cuchillo, un mapa de la ciudad en la que creciste, un ratón como mascota, un símbolo para recordar a tus padres, una muda de ropa común y una bolsa con 10po.",
                          "Rasgo": "SECRETOS DE LA CIUDAD Conoces los patrones y flujos secretos de las ciudades, y puedes encontrar pasadizos a través de la masa urbana que otros pasarían por alto. Cuando no estás en combate, puedes viajar (junto a los compañeros que guíes) a través de dos puntos en la ciudad el doble de rápido de lo que tu velocidad te permitiría normalmente."
                          },
              "Marinero": {"Habilidades":["Atletismo", "Percepción"],
                           "Herramientas_a_elegir": 2,
                          "Herramientas":["herramientas de navegación", "vehículos (acuáticos)"],
                           "Idiomas_a_elegir": 0,
                          "Idiomas":[],
                          "Equipo": " una barra de madera o metal (una clava), 50 pies de cuerda de seda, un amuleto de la suerte, como una pata de conejo o una piedra pequeña con un agujero en el centro (o podrías tirar una baratija aleatoria en la tabla Baratijas en el Capítulo 5), una muda de ropa común y una bolsa con 10 po.",
                          "Rasgo": "PASAJE MARÍTIMO Cuando lo necesites, puedes asegurar un pasaje gratis en un barco para ti y tus compañeros de aventuras. Podrías navegar en la nave en la que serviste, o en otra nave con la que tengas buenas relaciones (quizá en una cuyo capitán fue tu compañero de tripulación). Ya que estás pidiendo un favor, no puedes asegurar un calendario o una ruta que cumpla con todas tus necesidades. Tu Dungeon Master determinará cuánto toma el llegar a donde necesites ir. A cambio de tu pasaje gratuito, se espera de ti y tus compañeros que sirvan a la tripulación durante el viaje."
                          },
              "Noble": {"Habilidades":["Historia", "Persuasión"],
                        "Herramientas_a_elegir": 1,
                          "Herramientas":["Juego de cartas", "Juego de dados", "Kits", "Kit de envenenador", "Kit de herborista"],
                        "Idiomas_a_elegir": 1,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "una muda de ropas finas, un anillo con sello, un pergamino con tu genealogía, y un monedero con 25 po.",
                          "Rasgo": "POSICIÓN DE PRIVILEGIO Gracias a tu cuna noble, la gente tiende a pensar lo mejor de ti. Eres bienvenido en la alta sociedad y la gente asume que tienes el derecho de estar donde quiera que estés. La gente común hace todo lo posible para que te sientas cómodo y evitar tu descontento, y otras personas de alta cuna te tratan como miembro de la misma esfera social. Puedes asegurar una audiencia con un noble local, si es necesario."
                          },
              "Sabio": {"Habilidades":["Arcano", "Historia"],
                        "Herramientas_a_elegir": 0,
                          "Herramientas":[],
                        "Idiomas_a_elegir": 2,
                          "Idiomas":["Común", "Enano", "Élfico", "Gigante", "Gnómico", "Goblin", "Mediano", "Orco", "Abisal", "Celestial", "Dracónico", "Habla Profunda",
                                     "Infernal", "Primordial", "Silvano", "Infracomún"],
                          "Equipo": "un tintero, una pluma, un cuchillo pequeño, una carta de un colega muerto con una pregunta que aún no ha sido capaz de responder, una muda de ropa común y una bolsa con 10 po.",
                          "Rasgo": "INVESTIGADOR Cuando intentas aprender o recordar un fragmento de información, si no sabes nada sobre el tema, a menudo sí sabes a dónde o de quién puedes obtenerlo. Por lo general, esta información viene de una biblioteca, scriptorium, universidad o un sabio u otra persona o criatura culta. Tu DM podría decidir que el conocimiento que buscas está oculto en un lugar lejano y casi inaccesible, o que simplemente no puede ser encontrado. Develar los secretos más profundos del multiverso puede requerir una aventura o incluso toda una campaña."
                        },
              "Soldado": {"Habilidades":["Atletismo", "Intimidación"],
                          "Herramientas_a_elegir": 2,
                          "Herramientas":["Juego de cartas", "Juego de dados", "vehículos (terrestres)"],
                          "Idiomas_a_elegir": 0,
                          "Idiomas":[],
                          "Equipo": "una insignia con tu rango, un trofeo tomado de un enemigo caído (una daga, una hoja rota o un trozo de un estandarte), un conjunto de dados de hueso o baraja de cartas, una muda de ropa común, y una bolsa que contiene 10 po.",
                          "Rasgo": "RANGO MILITAR Tienes un rango militar de tu carrera como soldado. Aquellos leales a tu antigua organización militar aún reconocen tu autoridad e influencia, y se dirigirán a ti con respeto si son de un rango inferior. Puedes invocar tu rango para ejercer influencia sobre los demás soldados y requisar equipo simple o caballos para un uso temporal. Generalmente también puedes tener acceso a los campamentos y fortalezas amistosas en las que se reconozca tu rango militar."
                          }
               }
